#!/bin/bash
Red='\033[1;91m'             # Red
BIGreen='\033[1;92m'           # Green
BIYellow='\033[1;93m'          # Yellow
BIBlue='\033[1;94m'            # Blue
BIPurple='\033[1;95m'          # Purple
BICyan='\033[1;96m'            # Cyan
NORMAL="\033[0;39m"

echo -e $BIPurple'Enter username which needs to be removed' $NORMAL
read username

cat userdel3.yml | sed "s/username/$username/g" > userdel2.yml
ansible-playbook userdel2.yml
sleep 3
