--- # Creating a groupadd playbook 
- hosts: twoservers
  become: true
  become_user: root
  vars: 
   group_name: twoservers
   group_idnum: 1034
  tasks:
  - name: Group add tasks
    group: name={{ group_name }} gid={{ group_idnum }} state=present

