#!/bin/bash
Red='\033[1;91m'             # Red
BIGreen='\033[1;92m'           # Green
BIYellow='\033[1;93m'          # Yellow
BIBlue='\033[1;94m'            # Blue
BIPurple='\033[1;95m'          # Purple
BICyan='\033[1;96m'            # Cyan
NORMAL="\033[0;39m"

echo -e $BIPurple'Please enter the group name' $NORMAL
read gname

echo -e $BIPurple'Please enter the group ID' $NORMAL
read gid

cat groupadd3.yml | sed "s/abcd/$gname/g" | sed "s/gidvalue/$gid/g"  > groupadd2.yml
ansible-playbook groupadd2.yml
sleep 3        
